### ISSUE TITLE
Support Terraform's --target flag

### ISSUE THREAD

**Issue by so0k** [hootsuite/atlantis#129]
I haven't tried this out yet, but is it possible to specify resource targets with `--target`? We use this heavily when making infrastructure updates

**Comment by lkysow** [comment]
@so0k you can append flags to `plan` using the `extra_arguments` configuration key in an `atlantis.yaml` config file living in your project (see https://github.com/hootsuite/atlantis#project-specific-customization).

So you could have

```yaml
# atlantis.yaml
extra_arguments:
- command: plan
  arguments:
  - "-target=TARGET"
```

But does it make sense to set this against an entire project or on different plan/apply runs do you need to set a target? In which case you'd like `-target` to be an option to the `atlantis plan` and `atlantis apply` commands?
