### ISSUE TITLE
Ability to ignore terraform files and folders from atlantis run

### ISSUE THREAD

**Issue by anubhavmishra** [hootsuite/atlantis#50]
Currently, atlantis ignores certain folders such as  `_modules/` and `modules/` but we want to extend this to ignore any folder that has `.atlantisignore` file or something along those lines. https://github.com/hootsuite/atlantis/blob/master/server/plan_executor.go#L196

**Comment by swladyka** [comment]
I like the option with .atlantisignore files very much, would be very helpful when working with terraform modules and having templates in a separate directory.

**Comment by anubhavmishra** [comment]
yea for sure. Currently, atlantis already ignores certain folders ex: `_modules/` and `modules/`. https://github.com/hootsuite/atlantis/blob/master/server/plan_executor.go#L196

**Comment by johntdyer** [comment]
So it seems like the fix in this ticket aws to rename your module folder to "**_modules**" or "**modules**" which would ignore them. However it looks like https://github.com/hootsuite/atlantis/pull/211 changed this behavior....  Any chance you guys could re-evaluate the .atlantisignore suggestion ?

**Comment by lkysow** [comment]
@johntdyer is the issue you're having that Atlantis is running `plan` in the parent directory of `modules/`? If so, I've fixed this in the new repo here: https://github.com/runatlantis/atlantis/pull/13. I'm working on Atlantis under that repo now and will soon be updating the tickets/README of this repo accordingly (if you're wondering why I've explained [here](https://medium.com/runatlantis/moving-atlantis-to-runatlantis-atlantis-on-github-4efc025bb05f)). You can grab the latest release here: https://github.com/runatlantis/atlantis/releases

Does that change fix your issue or is there something else happening?

Regarding .atlantisignore, here's the direction I want to go:
* in an upcoming release of Atlantis, we'll support automatically running plan on a new pull request
* if there's no `atlantis.yaml` in the repo, then we'll attempt to figure out where to run plan following the current logic
* if there *is* an `atlantis.yaml`, then you can configure where we run plan and on what changes using some new config options:
```yaml
version: 2
pipelines:
  plan:
    on_push:
      enabled: true
      when_modified: ["*.tf", "../../modules/**/*.tf"] # If a modified file matches then we'll run plan in this project. Uses .gitignore syntax. It's optional, if not specified then will default to ["*.tf", "**/*.tfvars"].
```

So long-story short, you could use the `when_modified` key to achieve the same behaviour as `.atlantisignore`. Would that work for you? Thanks!
